core/urls.py
from django.urls import path, include
from .views import *
from . import api_views
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register('items', api_views.ItemModelViewSet, basename='items')
router.register('users', api_views.UserModelViewSet, basename='users')


app_name = 'core'

urlpatterns = [
    path('', home, name='home'),
    path('about/', about, name='about'),
    path('products/', ProductsView.as_view(), name='products'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<int:pk>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<int:pk>/', add_to_cart, name='add-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<int:pk>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<int:pk>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('testpayment/', PaymentTestView.as_view(), name='payment_test'),
    path('request-refund/<slug:ref_code>',
         RequestRefundView.as_view(), name='request-refund'),
    path('orders/', OrdersView.as_view(), name='orders'),
    path('api/', include(router.urls)),
]
#     path('shirts/', HomeShirtView.as_view(), name='home_shirt'),
#     path('sports/', HomeSportView.as_view(), name='home_sports'),
#     path('casuals/', HomeCasualView.as_view(), name='home_casuals'),

djecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('api-auth/', include('rest_framework.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block head_title %}{% endblock %}</title>
  {% block extra_head %}
  {% endblock %}
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
  <link rel='stylesheet' href="{% static 'css/style.css' %}" />
</head>

<body>

  {% include 'navbar.html'%}
  {% if messages %}
  {% for message in messages %}
  <div class="notification is-success {{ message.tags }}">
    <button class="delete"></button>
    {{ message }}
  </div>
  {% endfor %}
  {% endif %}


  {% block content %}
  {% endblock content %}

  {% block extra_body %}
  {% endblock %}

  {% include "footer.html" %}
  {% include "scripts.html" %}

  {% block extra_scripts %}
  {% endblock extra_scripts %}




</body>

</html>

templates/checkout.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block extra_head %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
  integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
{% endblock %}

{% block content %}

<main>
  <div class="container wow fadeIn">
    <h2 class="my-5 h2 text-center">Checkout form</h2>
    <div class="row">
      <div class="col-md-8 mb-4">
        <div class="card">
          <form method="POST" class="card-body">
            {% csrf_token %}

            <h3>Shipping address</h3>

            <div class='hideable_shipping_form'>

              <div class="md-form mb-5">
                <input type='text' placeholder='1234 Main St' id='shipping_address' name='shipping_address'
                  class='form-control' />
                <label for="shipping_address" class="">Address</label>
              </div>

              <div class="md-form mb-5">
                <input type='text' placeholder='Apartment or suite' id='shipping_address2' name='shipping_address2'
                  class='form-control' />
                <label for="shipping_address2" class="">Address 2 (optional)</label>
              </div>

              <div class="row">
                <div class="col-lg-4 col-md-12 mb-4">
                  <label for="country">Country</label>
                  {{ form.shipping_country }}
                  <div class="invalid-feedback">
                    Please select a valid country.
                  </div>
                </div>
                <div class="col-lg-4 col-md-6 mb-4">
                  <label for="shipping_zip">Zip</label>
                  <input type='text' placeholder='Zip code' id='shipping_zip' name='shipping_zip'
                    class='form-control' />
                  <div class="invalid-feedback">
                    Zip code required.
                  </div>
                </div>
              </div>

              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="same_billing_address"
                  id="same_billing_address">
                <label class="custom-control-label" for="same_billing_address">Billing address is the same as my
                  shipping address</label>
              </div>
              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="set_default_shipping"
                  id="set_default_shipping">
                <label class="custom-control-label" for="set_default_shipping">Save as default shipping address</label>
              </div>

            </div>

            {% if default_shipping_address %}
            <div class="custom-control custom-checkbox">
              <input type="checkbox" class="custom-control-input" name="use_default_shipping" id="use_default_shipping">
              <label class="custom-control-label" for="use_default_shipping">Use default shipping address:
                {{ default_shipping_address.street_address|truncatechars:10 }}</label>
            </div>
            {% endif %}

            <hr>

            <h3>Billing address</h3>

            <div class='hideable_billing_form'>
              <div class="md-form mb-5">
                <input type='text' placeholder='1234 Main St' id='billing_address' name='billing_address'
                  class='form-control' />
                <label for="billing_address" class="">Address</label>
              </div>

              <div class="md-form mb-5">
                <input type='text' placeholder='Apartment or suite' id='billing_address2' name='billing_address2'
                  class='form-control' />
                <label for="billing_address2" class="">Address 2 (optional)</label>
              </div>

              <div class="row">
                <div class="col-lg-4 col-md-12 mb-4">
                  <label for="country">Country</label>
                  {{ form.billing_country }}
                  <div class="invalid-feedback">
                    Please select a valid country.
                  </div>
                </div>

                <div class="col-lg-4 col-md-6 mb-4">
                  <label for="billing_zip">Zip</label>
                  <input type='text' placeholder='Zip code' id='billing_zip' name='billing_zip' class='form-control' />
                  <div class="invalid-feedback">
                    Zip code required.
                  </div>
                </div>

              </div>

              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="set_default_billing" id="set_default_billing">
                <label class="custom-control-label" for="set_default_billing">Save as default billing address</label>
              </div>

            </div>

            {% if default_billing_address %}
            <div class="custom-control custom-checkbox">
              <input type="checkbox" class="custom-control-input" name="use_default_billing" id="use_default_billing">
              <label class="custom-control-label" for="use_default_billing">Use default billing address:
                {{ default_billing_address.street_address|truncatechars:10 }}</label>
            </div>
            {% endif %}
            <hr>

            <h3>Payment option</h3>

            <div class="d-block my-3">
              {% for value, name in form.fields.payment_option.choices %}
              <div class="custom-control custom-radio">
                <input id="{{ name }}" name="payment_option" value="{{ value }}" type="radio"
                  class="custom-control-input" required>
                <label class="custom-control-label" for="{{ name }}">{{ name }}</label>
              </div>
              {% endfor %}
            </div>

            <hr class="mb-4">
            <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>

          </form>

        </div>

      </div>

      <div class="col-md-4 mb-4">
        {% include "order_snippet.html" %}
      </div>

    </div>

  </div>
</main>

{% endblock content %}

{% block extra_scripts %}
<script>
  var hideable_shipping_form = $('.hideable_shipping_form');
  var hideable_billing_form = $('.hideable_billing_form');

  var use_default_shipping = document.querySelector("input[name=use_default_shipping]");
  var use_default_billing = document.querySelector("input[name=use_default_billing]");

  use_default_shipping.addEventListener('change', function () {
    if (this.checked) {
      hideable_shipping_form.hide();
    } else {
      hideable_shipping_form.show();
    }
  })

  use_default_billing.addEventListener('change', function () {
    if (this.checked) {
      hideable_billing_form.hide();
    } else {
      hideable_billing_form.show();
    }
  })
</script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
</script>

{% endblock extra_scripts %}

templates/footer.html
<footer>
</footer>

templates/home.html
{% extends "base.html" %}
{% block head_title %}
SpiceStore - Home
{% endblock %}
{% block content %}
<section class="landing">
    <div class="container-box">
        <center>
        <h2 class="title is-2 has-text-link-light"> SamSpices</h2> </center>
        <p class="subtitle is-3 has-text-link-light">We believe great flavors begin with great ingredients. Delivering classic and authentic spices that help products and the brands behind them satisfy consumer cravings.</p>
        <div class="is-flex is-justify-content-center is-align-content-center">
            <a href="/products" class="button is-info are-large is-rounded ">Explore</a>
        </div>

    </div>
</section>
{% endblock content %}

templates/navbar.html
{% load cart_template_tags %}

{% load static %}
<nav class="navbar is-transparent" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="#">
      <img src='{% static "img/spices_logo.png" %}' width="28" height="28">
      <h1 class="title is-3 p-2">SamSpices</h1>
    </a>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasic">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasic" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item is-tab" id="hometab" href="/">
        Home
      </a>

      <a class="navbar-item is-tab" id="abouttab" href="/products">
        Products
      </a>
      <a class="navbar-item is-tab" id="abouttab" href="/about">
        About
      </a>



    </div>
    <div class="navbar-end">
      {% if request.user.is_authenticated %}
      <a class="navbar-item is-tab mr-1" id="orderstab" href="{% url 'core:orders' %}">
        <i class="fas fa-boxes mr-1"></i>
        <span class="is-clearfix d-none is-inline-block-mobile"> Orders </span>

      </a>
      <a class="navbar-item is-tab" id="carttab" href="{% url 'core:order-summary' %}">
        <span class="tag is-danger mr-1"> {{ request.user|cart_item_count }} </span>
        <i class="fas fa-shopping-cart mr-1"></i>
        <span class="is-clearfix d-none is-inline-block-mobile"> Cart </span>
      </a>
      <a class="navbar-item is-tab" id="logouttab" href="{% url 'account_logout' %}">
        <span class="is-clearfix d-none is-inline-block-mobile"> Logout </span>
      </a>
      {% else %}

      <div class="navbar-item">
        <div class="buttons">
          <a class="button is-primary" href="{% url 'account_signup' %}">
            <strong>Sign up</strong>
          </a>
          <a class="button is-light" href="{% url 'account_login' %}">
            Log in
          </a>
        </div>
        {% endif %}

      </div>
    </div>
  </div>
</nav>

templates/order_snippet.html
<div class="col-md-12 mb-4">
    <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="text-muted">Your cart</span>
        <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
    </h4>
    <ul class="list-group mb-3 z-depth-1">
        {% for order_item in order.items.all %}
        <li class="list-group-item d-flex justify-content-between lh-condensed">
            <div>
                <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.title}}</h6>
                <small class="text-muted">{{ order_item.item.description}}</small>
            </div>
            <span class="text-muted">Rs {{ order_item.get_final_price }}</span>
        </li>
        {% endfor %}
        {% if order.coupon %}
        <li class="list-group-item d-flex justify-content-between bg-light">
            <div class="text-success">
                <h6 class="my-0">Promo code</h6>
                <small>{{ order.coupon.code }}</small>
            </div>
            <span class="text-success">-Rs {{ order.coupon.amount }}</span>
        </li>
        {% endif %}
        <li class="list-group-item d-flex justify-content-between">
            <span>Total (INR)</span>
            <strong>Rs {{ order.get_total }}</strong>
        </li>
    </ul>

    {% if DISPLAY_COUPON_FORM %}
    <form class="card p-2" action="{% url 'core:add-coupon' %}" method="POST">
        {% csrf_token %}
        <div class="input-group">
            {{ couponform.code }}
            <div class="input-group-append">
                <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
            </div>
        </div>
    </form>
    {% endif %}

</div>

templates/order_summary.html
{% extends "base.html" %}
{% block head_title %}
SpiceStore - Order Summary
{% endblock %}
{% block extra_head %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
{% endblock %}
{% block content %}
<main>
    <div class="container">

        <div class="table-responsive text-nowrap">
            <h2>Order Summary</h2>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Item title</th>
                        <th scope="col">Price</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Total Item Price</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order_item in object.items.all %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ order_item.item.title }}</td>
                        <td>Rs{{ order_item.item.price }}</td>
                        <td>
                            <a href="{% url 'core:remove-single-item-from-cart' order_item.item.pk %}"><i
                                    class="fas fa-minus mr-2"></i></a>
                            {{ order_item.quantity }}
                            <a href="{% url 'core:add-to-cart' order_item.item.pk %}"><i
                                    class="fas fa-plus ml-2"></i></a>
                        </td>
                        <td>
                            {% if order_item.item.discount_price %}
                            Rs {{ order_item.get_total_discount_item_price }}
                            <span class="badge badge-primary">Saving Rs {{ order_item.get_amount_saved }}</span>
                            {% else %}
                            Rs {{ order_item.get_total_item_price }}
                            {% endif %}
                            <a style='color: red;' href="{% url 'core:remove-from-cart' order_item.item.pk %}">
                                <i class="fas fa-trash float-right"></i>
                            </a>
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan='5'>Your cart is empty</td>
                    </tr>
                    <tr>
                        <td colspan="5">
                            <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
                        </td>
                    </tr>
                    {% endfor %}
                    {% if object.coupon %}
                    <tr>
                        <td colspan="4"><b>Coupon</b></td>
                        <td><b>-Rs {{ object.coupon.amount }}</b></td>
                    </tr>
                    {% endif %}
                    {% if object.get_total %}
                    <tr>
                        <td colspan="4"><b>Order Total</b></td>
                        <td><b>Rs {{ object.get_total }}</b></td>
                    </tr>
                    <tr>
                        <td colspan="5">
                            <a class='btn btn-warning float-right ml-2' href='/checkout/'>Proceed to checkout</a>
                            <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
                        </td>
                    </tr>
                    {% endif %}
                </tbody>
            </table>

        </div>

    </div>
</main>

{% endblock content %}
{% block extra_scripts %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
</script>
{% endblock %}

templates/orders.html
{% extends "base.html" %}
{% block head_title %}
SpiceStore - Orders
{% endblock %}
{% block extra_head %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
{% endblock %}

{% block content %}
<main>
    <div class="container">

        <div class="table-responsive text-nowrap">
            <h2>Orders History</h2>
            <table class="table">
                <thead>
                    <tr class="table-danger">
                        <th scope=" col">#</th>
                        <th scope="col">Item title</th>
                        <th scope="col">Item Price</th>
                        <th scope="col">Offer Price</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Total Item Price</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order in orders %}
                    <tr class="table-warning">
                        <td colspan="4">{{order.get_order_ref}} &emsp;&emsp; {{order.get_order_date}} &emsp;&emsp;
                            {{order.get_order_status_text}}</td>

                        <td colspan="2">
                            {% if order.refund_granted %}
                            <a class='btn btn-success float-right bg-dark text-white' href=""> Refunded</a>
                            {% elif order.is_on_refund_period %}
                            <a class='btn btn-primary float-right bg-dark text-white'
                                href="{% url 'core:request-refund' order.ref_code %}">Request
                                Refund</a>
                            {% else %}
                            <a class='btn btn-danger float-right bg-dark text-white' href=""> Return Window Closed</a>

                            {% endif %}
                        </td>
                    </tr>
                    {% for order_item in order.items.all %}
                    <tr>
                        <th scope=" row">{{ forloop.counter }}</th>
                        <td>{{ order_item.item.title }}</td>
                        <td>Rs {{ order_item.item.price }}</td>
                        <td>Rs {{ order_item.item.discount_price }}</td>
                        <td>
                            {{ order_item.quantity }}

                        </td>
                        <td>
                            {% if order_item.item.discount_price %}
                            Rs {{ order_item.get_total_discount_item_price }}

                            {% else %}
                            Rs {{ order_item.get_total_item_price }}
                            {% endif %}

                        </td>
                    </tr>

                    {% endfor %}
                    {% if order.coupon %}
                    <tr class="table-success">
                        <td colspan="5"><b>Coupon</b></td>
                        <td><b>-Rs {{ order.coupon.amount }}</b></td>
                    </tr>
                    {% endif %}
                    {% if order.get_total %}
                    <tr class="table-primary">
                        <td colspan="5"><b>Order Total</b></td>
                        <td><b>Rs {{ order.get_total }}</b></td>
                    </tr>

                    {% endif %}
                    <tr>
                        <td colspan="6"><b></b></td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan='6'>No orders</td>
                    </tr>
                    <tr>
                        <td colspan="6">
                            <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

        </div>

    </div>
</main>

{% endblock content %}
{% block extra_scripts %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
</script>
{% endblock %}

templates/prem.html
 <!--Grid row-->
 <div class="row d-flex justify-content-center wow fadeIn">

     <!--Grid column-->
     <div class="col-md-6 text-center">

         <h4 class="my-4 h4">Additional information</h4>

         <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
             voluptates,
             quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

     </div>
     <!--Grid column-->

 </div>
 <!--Grid row-->
 <!--Grid row-->

 <div class="row wow fadeIn">

     <!--Grid column-->
     <div class="col-lg-4 col-md-12 mb-4">

         <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">

     </div>
     <!--Grid column-->

     <!--Grid column-->
     <div class="col-lg-4 col-md-6 mb-4">

         <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">

     </div>
     <!--Grid column-->

     <!--Grid column-->
     <div class="col-lg-4 col-md-6 mb-4">

         <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">

     </div>
     <!--Grid column-->

 </div>
 <!--Grid row-->

templates/product.html
{% extends "base.html" %}
{% block head_title %}
SpiceStore - {{object.title}}
{% endblock %}
{% block content %}
<main class="mt-5 pt-4">
  <div class="tile is-ancestor ">
    <div class="tile is-vertical is-6">
      <div class="tile">
        <div class="tile is-parent">
          <article class="tile is-child ">
            <figure class="image product-image">
              <img src="{{ object.image.url }}">
            </figure>
          </article>
        </div>
      </div>
      <div class="tile is-parent">
        <article class="tile is-child">
          <div class="content">
            <!-- Content -->
          </div>
        </article>
      </div>
    </div>
    <div class="tile is-parent">
      <article class="tile is-child notification">
        <div class="content">
          <p class="title">{{object.title}}</p>
          <p class="subtitle"> {% if object.discount_price %}
            <span>
              <s>Rs{{ object.price }}</s>
            </span>
            <span>Rs{{ object.discount_price }}</span>
            {% else %}
            <span>Rs{{ object.price }}</span>
            {% endif %}</p>

          {% comment %} <form class="">
            <div class="field">
              <div class="control">
                <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
              </div>
              <div class="control">
                <button class="button is-primary" type="submit">
                  Add to cart
                  <i class="fas fa-shopping-cart ml-1"></i>
                </button>
              </div>
            </div>




          </form> {% endcomment %}
          <a href="{{ object.get_add_to_cart_url }}" class="button is-primary">
            Add to cart
            <i class="fas fa-shopping-cart ml-1"></i>
          </a>
          <a href="{{ object.get_remove_from_cart_url }}" class="button is-danger">
            Remove from cart
          </a>
          <div class="content">
            <p class="subtitle mt-6">Description</p>
            <p>{{ object.description }}</p>
          </div>
        </div>
      </article>
    </div>
  </div>
</main>



{% endblock content %}

templates/request_refund.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <main>
    <div class="container">

    <h2>Request Refund</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class='btn btn-primary'>Submit</button>
    </form>

    </div>
  </main>

{% endblock content %}

templates/scripts.html
{% load static %}

<script type="text/javascript" src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script>
  $(document).ready(function () {

    // Check for click events on the navbar burger icon
    $(".navbar-burger").click(function () {

      // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
      $(".navbar-burger").toggleClass("is-active");
      $(".navbar-menu").toggleClass("is-active");

    });
  });
  document.addEventListener('DOMContentLoaded', () => {
    (document.querySelectorAll('.notification .delete') || []).forEach(($delete) => {
      const $notification = $delete.parentNode;

      $delete.addEventListener('click', () => {
        $notification.parentNode.removeChild($notification);
      });
    });
  });
  // var active_tab = '<%- active%>';
  // if (active_tab === 'home') {
  //     var element = document.getElementById("hometab");
  //     element.classList.add("is-active");
  // } else if (active_tab === 'about') {
  //     var element = document.getElementById("abouttab");
  //     element.classList.add("is-active");
  // }
</script>